### PR TITLE
For some reason in juce it seems that all signals must be re-registred 

### PR DESCRIPTION
**Pull request by KjellKod**
re-registration per thread doesn't hurt in either case.   Ive tested this with 50ms or shorter interval and it seems to work for SIGTERM, SIGABRT, AccessViolation 

Hopefully this was the last issue. Please let me know if you find more.

### CODE REVIEW

**Comment by Hurleyworks** [comment]
>
> re-registration per thread doesn't hurt in either case. Ive tested this
> with 50ms or shorter interval and it seems to work for SIGTERM, SIGABRT,
> AccessViolation


I confirm it's working here too with shorter intervals now. Thanks!

I just tried using the new g3log in my project and have hit a weird
problem. My project is a plugin (.dll ) and when the host app(LightWave)
activates a certain feature on a new thread it seems to throw an exception
on the thread naming function(stack dump[7])  just like JUCE did. How
bizarre! I'm pretty sure LW does not use JUCE, but I'm on their beta team
so I'll ask.

The older g3log does not crash here. Do you have any theory why that might
be?  Unfortunately this is a showstopper for me

2015/02/03 06:37:28.4621289 INFO [LWEventHandler.cpp L: 352]
> "LWEVNT_VIEWPORT_OBJECT_ADDED"
> 2015/02/03 06:37:28.5042085
> ***** FATAL EXCEPTION RECEIVED *******
> "
> ***** Received fatal exception Unknown/1080890248 PID: 8312
> ******* STACKDUMP *******
> stack dump [0] e:\code\3rdparty\g3logger\source\stacktrace_windows.cpp L:
> 168 stacktrace::stackdump
> stack dump [1] e:\code\3rdparty\g3logger\source\crashhandler_windows.cpp
> L: 77 `anonymous namespace'::exceptionHandling
> stack dump [2] e:\code\3rdparty\g3logger\source\crashhandler_windows.cpp
> L: 105 `anonymous namespace'::vectorExceptionHandling
> stack dump [3] RtlLookupFunctionEntry
> stack dump [4] RtlRaiseException
> stack dump [5] RtlRaiseException
> stack dump [6] RaiseException
> stack dump [7] MTUtilSetThreadName
> stack dump [8] getVertexBoneWeight
> stack dump [9] QThread::setPriority
> stack dump [10] endthreadex
> stack dump [11] endthreadex
> stack dump [12] BaseThreadInitThunk
> stack dump [13] RtlUserThreadStart
> Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:
>  Unknown/1080890248
> Log content flushed flushed sucessfully to sink






On Mon, Feb 2, 2015 at 11:47 PM, Kjell Hedstrom <notifications@github.com>
wrote:

> re-registration per thread doesn't hurt in either case. Ive tested this
> with 50ms or shorter interval and it seems to work for SIGTERM, SIGABRT,
> AccessViolation
>
> Hopefully this was the last issue. Please let me know if you find more.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Hurleyworks/JuceApp/pull/2
> Commit Summary
>
>    - For some reason in juce it seems that all signals must be
>    re-registred per thread
>
> File Changes
>
>    - *M* Source/g3log/crashhandler_windows.cpp
>    <https://github.com/Hurleyworks/JuceApp/pull/2/files#diff-0> (26)
>    - *M* Source/g3log/stacktrace_windows.cpp
>    <https://github.com/Hurleyworks/JuceApp/pull/2/files#diff-1> (36)
>    - *M* Source/g3log/stacktrace_windows.hpp
>    <https://github.com/Hurleyworks/JuceApp/pull/2/files#diff-2> (2)
>
> Patch Links:
>
>    - https://github.com/Hurleyworks/JuceApp/pull/2.patch
>    - https://github.com/Hurleyworks/JuceApp/pull/2.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
> The older g3log does not crash here.

How old? 4 days ago?
Before any of the g3log changes with the crashhandling?

> Do you have any theory why that might 
> be? Unfortunately this is a showstopper for me
Last time it seemed it was the vectored exception handler that caused a this

Comment out the line to install 
AddVectoredExceptionHandler
I crashhandler_windows.cpp

If it's the same issue then you should be good. If it fixes it then you they are throwing without catching since I changed it in g3log to be the "last receiver" on the chain of vectored exception receivers

Is anything in their dll installed or initialized"before" or after g3log initialization?=

**Comment by KjellKod** [comment]
See inline reply

> My project is a plugin (.dll ) and when the host app(LightWave) 
> activates a certain feature on a new thread it seems to throw an exception 
> on the thread naming function(stack dump[7]) just like JUCE did. How 
> bizarre!

It's all related to order of exception handling I think. Please check with their beta team if that's the case. Maybe they can state their "execution handling order" expectations?

Please also comment out the insides of the function
ReverseToOriginalFatalHandling() 
It might mess up (again) the order of handlers=

**Comment by KjellKod** [comment]
It's an "unknown exception" which only means that's not the list of "expected" Windows OS exceptions. The ID number is given in the log so it that might give some extra guidance

**Comment by Hurleyworks** [comment]
>
> How old? 4 days ago?
> Before any of the g3log changes with the crashhandling?


I used a copy of the Master branch I saved before you merged the "windows
crash handler" branch.

Comment out the line to install
> AddVectoredExceptionHandler


That seems to fix everything  Whew! :)


On Tue, Feb 3, 2015 at 8:40 AM, Kjell Hedstrom <notifications@github.com>
wrote:

>
> > The older g3log does not crash here.
>
> How old? 4 days ago?
> Before any of the g3log changes with the crashhandling?
>
> > Do you have any theory why that might
> > be? Unfortunately this is a showstopper for me
> Last time it seemed it was the vectored exception handler that caused a
> this
>
> Comment out the line to install
> AddVectoredExceptionHandler
> I crashhandler_windows.cpp
>
> If it's the same issue then you should be good. If it fixes it then you
> they are throwing without catching since I changed it in g3log to be the
> "last receiver" on the chain of vectored exception receivers
>
> Is anything in their dll installed or initialized"before" or after g3log
> initialization?=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-72651425>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
> On Feb 3, 2015, at 7:52 AM, Steve Hurley <notifications@github.com> wrote:
> 
> Comment out the line to install 
> > AddVectoredExceptionHandler 
> 
> 
> That seems to fix everything Whew! :)

I suspected as much. Glad to hear we have a short-cut fix.

Unless I figure out a way to make this safe, which I thought I had, I will make the vectored exception handling an option that is by default disabled.

There are two really annoying things here:
1) exceptions seems to be used in windows frameworks as a "means of communication" rather than an "exceptional and bad event".
I can't do anything about this unfortunate practice except maybe curse Java influence and some teeth gnashing.

2) I was sure that when I fixed it for Juce it actually took care of this. So that an exception could propagate past g3log.
I will revise this code and see how it should be handled. 


A potential fix 
Maybe an "unknown" exception should just be totally ignored by g3log? (maybe adding a LOG(WARNING)).  

That should  have fixed this for both Juce and your current 3rdpart library.

Does that sound OK?=

**Comment by Hurleyworks** [comment]
>
> Maybe an "unknown" exception should just be totally ignored by g3log?
> (maybe adding a LOG(WARNING)).
> That should have fixed this for both Juce and your current 3rdpart
> library.


That sounds like a good plan to me.

Unless I figure out a way to make this safe, which I thought I had, I will
> make the vectored exception handling an option that is by default disabled.


Yes, I was going to suggest that too.

On Tue, Feb 3, 2015 at 10:06 AM, Kjell Hedstrom <notifications@github.com>
wrote:

>
> > On Feb 3, 2015, at 7:52 AM, Steve Hurley <notifications@github.com>
> wrote:
> >
> > Comment out the line to install
> > > AddVectoredExceptionHandler
> >
> >
> > That seems to fix everything Whew! :)
>
> I suspected as much. Glad to hear we have a short-cut fix.
>
> Unless I figure out a way to make this safe, which I thought I had, I will
> make the vectored exception handling an option that is by default disabled.
>
> There are two really annoying things here:
> 1) exceptions seems to be used in windows frameworks as a "means of
> communication" rather than an "exceptional and bad event".
> I can't do anything about this unfortunate practice except maybe curse
> Java influence and some teeth gnashing.
>
> 2) I was sure that when I fixed it for Juce it actually took care of this.
> So that an exception could propagate past g3log.
> I will revise this code and see how it should be handled.
>
>
> A potential fix
> Maybe an "unknown" exception should just be totally ignored by g3log?
> (maybe adding a LOG(WARNING)).
>
> That should have fixed this for both Juce and your current 3rdpart
> library.
>
> Does that sound OK?=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-72665979>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
I tested without vectored exception handling the g3log-FATAL-choice.

*Good news* is that all fatal exceptions were caught for safe shutdown of
the logger and app.
*Bad news* is that the backtrace is not nearly as good for several of the
fatal events.

Ive a good idea about what to do and will work with his later this week. I
trust that the workaround
is good enough for now (right?)

Cheers
Kjell



**Contact Information**
*Mobile:  +1 - 617.378.1915*

*E-mail: Hedstrom@KjellKod.cc*

**Comment by Hurleyworks** [comment]
>
> . I trust that the workaround is good enough for now (right?)


Sure, no worries here.

The only problem I have is that  now that g3log has the capability to
pinpoint where the intermittent mystery crashes are occurring in my
project, I can't seem to hit them anymore. :)

On Wed, Feb 4, 2015 at 1:04 AM, Kjell Hedstrom <notifications@github.com>
wrote:

> I tested without vectored exception handling the g3log-FATAL-choice.
>
> *Good news* is that all fatal exceptions were caught for safe shutdown of
> the logger and app.
> *Bad news* is that the backtrace is not nearly as good for several of the
> fatal events.
>
> Ive a good idea about what to do and will work with his later this week. I
> trust that the workaround
> is good enough for now (right?)
>
> Cheers
> Kjell
>
>
>
> **Contact Information**
> *Mobile: +1 - 617.378.1915*
>
> *E-mail: Hedstrom@KjellKod.cc*
>
>
> On Tue, Feb 3, 2015 at 8:20 AM, Steve Hurley <notifications@github.com>
>
> wrote:
>
> > >
> > > Maybe an "unknown" exception should just be totally ignored by g3log?
> > > (maybe adding a LOG(WARNING)).
> > > That should have fixed this for both Juce and your current 3rdpart
> > > library.
> >
> >
> > That sounds like a good plan to me.
> >
> > Unless I figure out a way to make this safe, which I thought I had, I
> will
> > > make the vectored exception handling an option that is by default
> > disabled.
> >
> >
> > Yes, I was going to suggest that too.
> >
> > On Tue, Feb 3, 2015 at 10:06 AM, Kjell Hedstrom <
> notifications@github.com>
> >
> > wrote:
> >
> > >
> > > > On Feb 3, 2015, at 7:52 AM, Steve Hurley <notifications@github.com>
> > > wrote:
> > > >
> > > > Comment out the line to install
> > > > > AddVectoredExceptionHandler
> > > >
> > > >
> > > > That seems to fix everything Whew! :)
> > >
> > > I suspected as much. Glad to hear we have a short-cut fix.
> > >
> > > Unless I figure out a way to make this safe, which I thought I had, I
> > will
> > > make the vectored exception handling an option that is by default
> > disabled.
> > >
> > > There are two really annoying things here:
> > > 1) exceptions seems to be used in windows frameworks as a "means of
> > > communication" rather than an "exceptional and bad event".
> > > I can't do anything about this unfortunate practice except maybe curse
> > > Java influence and some teeth gnashing.
> > >
> > > 2) I was sure that when I fixed it for Juce it actually took care of
> > this.
> > > So that an exception could propagate past g3log.
> > > I will revise this code and see how it should be handled.
> > >
> > >
> > > A potential fix
> > > Maybe an "unknown" exception should just be totally ignored by g3log?
> > > (maybe adding a LOG(WARNING)).
> > >
> > > That should have fixed this for both Juce and your current 3rdpart
> > > library.
> > >
> > > Does that sound OK?=
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-72665979>.
> > >
> >
> >
> >
> > --
> > -Steve
> > http://www.hurleyworks.com
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-72668472>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-72795748>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
Hi Steve,

I've got some good news for you.


>
> *The only problem I have is that now that g3log has the capability to
> pinpoint where the intermittent mystery crashes are occurring in my
> project, I can't seem to hit them anymore. :)*
>

I've added to github.com/KjellKod/g3log, branch *windows-vector-exceptions
 *an improved vectored exception handling.  I expect it to merge it to
master within an hour or so.

In the updated code any vectored exception that is unknown is just ignored.
It  skips the handling of it,... which will later be caught by the "unknown
exception handler" if no other handler has intervened.  I think this should
solve the issue you had with other libraries being creative with
exceptions.

You can also disable the vectored exception handling. It's as easy as using
a define "*DISABLE_VECTORED_EXCEPTIONHANDLING*"    in the source code or if
you do it from cmake.  "*cmake -DENABLE_VECTORED_EXCEPTIONHANDLING=OFF*"

The issue with not seeing the full stack trace on Windows when building in
Release mode has to do that the .pdb (symbol) file is not generated.  I'm
not sure yet how to do this from CMake, but in a Visual Studio project you
can create this in the following manner.

Choose properties on your project. Make sure that the "Active"
configuration is Release.  Choose:  Linker ->  Debugging.    In "Generate
Debug Info".  Select "Yes".

After a full rebuild the .pdb file, or "Source Browser Database" is
generated.  It won't give a perfect stack trace but it's still better.

The thing to remember is that hte .pdb file must be installed where the
program is installed otherwise, in case of a crash, it cannot use the
"source browser database" to do the symbol lookup.

Compare:
Release stacktrace
***** Vectored Exception Handler: Received fatal exception
EXCEPTION_ACCESS_VIOLATION   PID: 7768

******* STACKDUMP *******
stack dump [0]
stack dump [1]   `anonymous namespace'::*CallExitFunction*
stack dump [2]   `anonymous namespace'::*ExecuteDeathFunction*
stack dump [3]   main
stack dump [4]          f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c L: 626
__tmainCRTStartup
stack dump [5]   BaseThreadInitThunk
stack dump [6]   RtlInitializeExceptionChain
stack dump [7]   RtlInitializeExceptionChain

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:
 EXCEPTION_ACCESS_VIOLATION
Log content flushed flushed sucessfully to sink



Debug stacktrace
***** Vectored Exception Handler: Received fatal exception
EXCEPTION_ACCESS_VIOLATION   PID: 7400

******* STACKDUMP *******
stack dump [0]
stack dump [1]          d:\programs(x86)\microsoft visual studio
12.0\vc\include\xrefwrap L: 382 std::_Callable_fun<void (__cdecl*const)(voi
d),0>::_ApplyX<void>
stack dump [2]          d:\programs(x86)\microsoft visual studio
12.0\vc\include\functional L: 229 std::_Func_impl<std::_Callable_fun<void (
__cdecl*const)(void),0>,std::allocator<std::_Func_class<void>
>,void>::_Do_call
stack dump [3]          d:\programs(x86)\microsoft visual studio
12.0\vc\include\functional L: 315 std::_Func_class<void>::operator()
stack dump [4]
 d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 119
`anonymous namespace'::*CallActualExitFunction*
stack dump [5]
 d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 122
`anonymous namespace'::*CallExitFunction*
stack dump [6]
 d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 146
`anonymous namespace'::*ExecuteDeathFunction*
stack dump [7]
 d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 214
`anonymous namespace'::ForwardChoiceForFatalExit
stack dump [8]
 d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 220
`anonymous namespace'::*ChooseFatalExit*
stack dump [9]
 d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 240 main
stack dump [10]         f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c L: 626
__tmainCRTStartup
stack dump [11]         f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c L: 466
mainCRTStartup
stack dump [12]  BaseThreadInitThunk
stack dump [13]  RtlInitializeExceptionChain
stack dump [14]  RtlInitializeExceptionChain

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:
 EXCEPTION_ACCESS_VIOLATION
Log content flushed flushed sucessfully to sink







**Contact Information**
*Mobile:  +1 - 617.378.1915*

*E-mail: Hedstrom@KjellKod.cc*

**Comment by Hurleyworks** [comment]
Hi Kjell,

Sorry for the delay. Sometimes life gets in the way of work. :)

The new changes sound great. I'll be able to check it out today.

The thing to remember is that hte .pdb file must be installed where the
> program is installed otherwise, in case of a crash, it cannot use the
> "source browser database" to do the symbol lookup.


The .pdb file for my project is over 100MB so I won't be able to distribute
it to end users but it will certainly be useful for in-house testing.

On Mon, Feb 16, 2015 at 4:16 AM, Kjell Hedstrom <notifications@github.com>
wrote:

> Hi Steve,
>
> I've got some good news for you.
>
>
> >
> > *The only problem I have is that now that g3log has the capability to
> > pinpoint where the intermittent mystery crashes are occurring in my
> > project, I can't seem to hit them anymore. :)*
> >
>
> I've added to github.com/KjellKod/g3log, branch *windows-vector-exceptions
> *an improved vectored exception handling. I expect it to merge it to
> master within an hour or so.
>
> In the updated code any vectored exception that is unknown is just ignored.
> It skips the handling of it,... which will later be caught by the "unknown
> exception handler" if no other handler has intervened. I think this should
> solve the issue you had with other libraries being creative with
> exceptions.
>
> You can also disable the vectored exception handling. It's as easy as using
> a define "*DISABLE_VECTORED_EXCEPTIONHANDLING*" in the source code or if
> you do it from cmake. "*cmake -DENABLE_VECTORED_EXCEPTIONHANDLING=OFF*"
>
> The issue with not seeing the full stack trace on Windows when building in
> Release mode has to do that the .pdb (symbol) file is not generated. I'm
> not sure yet how to do this from CMake, but in a Visual Studio project you
> can create this in the following manner.
>
> Choose properties on your project. Make sure that the "Active"
> configuration is Release. Choose: Linker -> Debugging. In "Generate
> Debug Info". Select "Yes".
>
> After a full rebuild the .pdb file, or "Source Browser Database" is
> generated. It won't give a perfect stack trace but it's still better.
>
> The thing to remember is that hte .pdb file must be installed where the
> program is installed otherwise, in case of a crash, it cannot use the
> "source browser database" to do the symbol lookup.
>
> Compare:
> Release stacktrace
> ***** Vectored Exception Handler: Received fatal exception
> EXCEPTION_ACCESS_VIOLATION PID: 7768
>
> ******* STACKDUMP *******
> stack dump [0]
> stack dump [1] `anonymous namespace'::*CallExitFunction*
> stack dump [2] `anonymous namespace'::*ExecuteDeathFunction*
> stack dump [3] main
> stack dump [4] f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c L: 626
> __tmainCRTStartup
> stack dump [5] BaseThreadInitThunk
> stack dump [6] RtlInitializeExceptionChain
> stack dump [7] RtlInitializeExceptionChain
>
> Exiting after fatal event (FATAL_EXCEPTION). Fatal type:
> EXCEPTION_ACCESS_VIOLATION
> Log content flushed flushed sucessfully to sink
>
>
>
> Debug stacktrace
> ***** Vectored Exception Handler: Received fatal exception
> EXCEPTION_ACCESS_VIOLATION PID: 7400
>
> ******* STACKDUMP *******
> stack dump [0]
> stack dump [1] d:\programs(x86)\microsoft visual studio
> 12.0\vc\include\xrefwrap L: 382 std::_Callable_fun<void (__cdecl*const)(voi
> d),0>::_ApplyX<void>
> stack dump [2] d:\programs(x86)\microsoft visual studio
> 12.0\vc\include\functional L: 229 std::_Func_impl<std::_Callable_fun<void (
> __cdecl*const)(void),0>,std::allocator<std::_Func_class<void>
> >,void>::_Do_call
> stack dump [3] d:\programs(x86)\microsoft visual studio
> 12.0\vc\include\functional L: 315 std::_Func_class<void>::operator()
> stack dump [4]
> d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 119
> `anonymous namespace'::*CallActualExitFunction*
> stack dump [5]
> d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 122
> `anonymous namespace'::*CallExitFunction*
> stack dump [6]
> d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 146
> `anonymous namespace'::*ExecuteDeathFunction*
> stack dump [7]
> d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 214
> `anonymous namespace'::ForwardChoiceForFatalExit
> stack dump [8]
> d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 220
> `anonymous namespace'::*ChooseFatalExit*
> stack dump [9]
> d:\bitbucket\___github\g3log\example\main_fatal_choice.cpp L: 240 main
> stack dump [10] f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c L: 626
> __tmainCRTStartup
> stack dump [11] f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c L: 466
> mainCRTStartup
> stack dump [12] BaseThreadInitThunk
> stack dump [13] RtlInitializeExceptionChain
> stack dump [14] RtlInitializeExceptionChain
>
> Exiting after fatal event (FATAL_EXCEPTION). Fatal type:
> EXCEPTION_ACCESS_VIOLATION
> Log content flushed flushed sucessfully to sink
>
>
>
>
>
>
>
> **Contact Information**
> *Mobile: +1 - 617.378.1915*
>
> *E-mail: Hedstrom@KjellKod.cc*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-74478840>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
> The new changes sound great. I'll be able to check it out today.

I got feedback from another user and I will try to address them this weekend.

Nothing serious
1) an vectored exception that is not fatal gets a LOG(WARNING)
---> I will remove the log statement 

2) CHECK(...) that triggers a fatal message and shutdown will get a breakpoint, similar to the signal and exception handling.


On a side note. When I publish these changes in a blog post, is it OK that I mention you (first name only) in a thank you section?

Cheers
Kjell

**Comment by Hurleyworks** [comment]
>
> In the updated code any vectored exception that is unknown is just ignored.
> It skips the handling of it,... which will later be caught by the "unknown
> exception handler" if no other handler has intervened. I think this should
> solve the issue you had with other libraries being creative with
> exceptions.


Yes it does. Unfortunately, as is often the case, I never got a response
from the LightWave developers about that problem so this is very much
appreciated!

The issue with not seeing the full stack trace on Windows when building in
> Release mode has to do that the .pdb (symbol) file is not generated


I experimented a little and the stack traces in Debug and Release modes
were almost exactly the same in most cases.  Excellent!

I had one case during a crash on exit where  my FatalExitHandler kept being
continuously called and I had to shut down LightWave via TaskManager. I'll
see if I can figure out what's going on there.

Do you have to do any more work to make these new features work on the
Mac?  About 25-30% of my users are on the Mac. I can set up an Xcode
project on the Juce App if you need help testing.

On a side note. When I publish these changes in a blog post, is it OK that
> I mention you (first name only) in a thank you section?


 Thanks!  No problem. I gave you credit and a link to g3log a while back on
the LightWave forum ...  although I admit  I was a little reluctant at
first to give away my competitive advantage to other developers. :)

On Sat, Feb 21, 2015 at 9:05 AM, Kjell Hedstrom <notifications@github.com>
wrote:

>
> > The new changes sound great. I'll be able to check it out today.
>
> I got feedback from another user and I will try to address them this
> weekend.
>
> Nothing serious
> 1) an vectored exception that is not fatal gets a LOG(WARNING)
> ---> I will remove the log statement
>
> 2) CHECK(...) that triggers a fatal message and shutdown will get a
> breakpoint, similar to the signal and exception handling.
>
>
> On a side note. When I publish these changes in a blog post, is it OK that
> I mention you (first name only) in a thank you section?
>
> Cheers
> Kjell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-75372996>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
> I had one case during a crash on exit where my FatalExitHandler kept being
> continuously called and I had to shut down LightWave via TaskManager. I'll
> see if I can figure out what's going on there.
You provided your own exit handler, right?
In that case make sure that the signal handler and exception handlers are replaced for what was before or the defaults (check ReverseToOriginalFatalHandling(...)) once a fatal event occurs 


> 
> Do you have to do any more work to make these new features work on the
> Mac? About 25-30% of my users are on the Mac. I can set up an Xcode
> project on the Juce App if you need help testing.

I haven't tested it on Mac in a long time. Since I don't have a Mac :(

If I come up with a way of making money on this (maybe for some "sink" libraries?, or getting a work salary raise)  I could upgrade my HW situation. Till then I'm "stuck" on Linux/Windows

I've tested it on Linux with Clang and gotten feedback from Mac users that it should work. Even sta

Breakpoints when catching a fatal event might be added later for Linux/Mac. Next up though is an easier way for users to install g3log as a library

**Comment by KjellKod** [comment]
Changes, not yet merged to master can be viewed in branch
https://github.com/KjellKod/g3log/tree/windows-vector-exceptions



1. LOG(WARNING) removed from unknown exceptions that are ignored in the
vectored exception handling.
2. CHECK(..expression_to_false...) will not trigger a break point.
    Instead I've added another hook which can either be used to trigger a
break point or to do *any* custom action on a fatal call.
    I.e. with this approach its easy for the user to add fatal cleanups
without having to override the fatal exit handler.

In g2log.hpp

      // Set a function-hook before a fatal message will be sent to the logger
      // i.e. this is a great place to put a break point, either in
your debugger
      // or programatically to catch LOG(FATAL), CHECK(...) or an OS
fatal event (exception or signal)
      // This will be reset to default (does nothing) at initializeLogging(...);
      //
      // Example usage for adding your own custom break point:      //
Windows: g2::SetPreFatalHook([]{__debugbreak();}); // remember
#include <intrin.h>
      // Linux:   g2::SetPreFatalHook([]{ raise(SIGTRAP); });
      void setFatalPreLoggingHook(std::function<void(void)>  pre_fatal_hook);







**Contact Information**
*Mobile:  +1 - 617.378.1915*

*E-mail: Hedstrom@KjellKod.cc*

**Comment by Hurleyworks** [comment]
>
> 1. LOG(WARNING) removed from unknown exceptions that are ignored in the
> vectored exception handling.


Thanks. I was going to complain about that too. :)

 2. CHECK(..expression_to_false...) will not trigger a break point.
> Instead I've added another hook which can either be used to trigger a
> break point or to do *any* custom action on a fatal call.
> I.e. with this approach its easy for the user to add fatal cleanups
> without having to override the fatal exit handler.


Excellent!.  That's very useful. One thing that I hit that was confusing
 was that when I set the hook to
g2::setFatalPreLoggingHook([]{__debugbreak(); }), then there's no g3log
file saved at all after a crash  when compiled in Release mode.

One minor nitpick. The example usage in g2log.hpp  uses a different
function name "SetPreFatalHook" instead of "setFatalPreLoggingHook".

* Example usage:
>    * Windows: g2::SetPreFatalHook([]{__debugbreak();}); // remember
> #include <intrin.h>
>    * Linux:   g2::SetPreFatalHook([]{ raise(SIGTRAP); });
>    */
>    void setFatalPreLoggingHook(std::function<void(void)>  pre_fatal_hook);


I've got JuceApp working on the Mac. I'll try to do some testing in the
next couple of days.

On Mon, Feb 23, 2015 at 3:21 PM, Kjell Hedstrom <notifications@github.com>
wrote:

> Changes, not yet merged to master can be viewed in branch
> https://github.com/KjellKod/g3log/tree/windows-vector-exceptions
>
>
>
> 1. LOG(WARNING) removed from unknown exceptions that are ignored in the
> vectored exception handling.
> 2. CHECK(..expression_to_false...) will not trigger a break point.
> Instead I've added another hook which can either be used to trigger a
> break point or to do *any* custom action on a fatal call.
> I.e. with this approach its easy for the user to add fatal cleanups
> without having to override the fatal exit handler.
>
> In g2log.hpp
>
> // Set a function-hook before a fatal message will be sent to the logger
> // i.e. this is a great place to put a break point, either in
> your debugger
> // or programatically to catch LOG(FATAL), CHECK(...) or an OS
> fatal event (exception or signal)
> // This will be reset to default (does nothing) at initializeLogging(...);
> //
> // Example usage for adding your own custom break point: //
> Windows: g2::SetPreFatalHook([]{__debugbreak();}); // remember
> #include <intrin.h>
> // Linux: g2::SetPreFatalHook([]{ raise(SIGTRAP); });
> void setFatalPreLoggingHook(std::function<void(void)> pre_fatal_hook);
>
>
>
>
>
>
>
> **Contact Information**
> *Mobile: +1 - 617.378.1915*
>
> *E-mail: Hedstrom@KjellKod.cc*
>
>
> On Sat, Feb 21, 2015 at 9:49 AM, Kjell Hedstrom <kjell.hedstrom@gmail.com>
> wrote:
>
>
> >
> > > I had one case during a crash on exit where my FatalExitHandler kept
> > being
> > > continuously called and I had to shut down LightWave via TaskManager.
> > I'll
> > > see if I can figure out what's going on there.
> > You provided your own exit handler, right?
> > In that case make sure that the signal handler and exception handlers are
> > replaced for what was before or the defaults (check
> > ReverseToOriginalFatalHandling(...)) once a fatal event occurs
> >
> >
> > >
> > > Do you have to do any more work to make these new features work on the
> > > Mac? About 25-30% of my users are on the Mac. I can set up an Xcode
> > > project on the Juce App if you need help testing.
> >
> > I haven't tested it on Mac in a long time. Since I don't have a Mac :(
> >
> > If I come up with a way of making money on this (maybe for some "sink"
> > libraries?, or getting a work salary raise) I could upgrade my HW
> > situation. Till then I'm "stuck" on Linux/Windows
> >
> > I've tested it on Linux with Clang and gotten feedback from Mac users
> that
> > it should work. Even sta
> >
> > Breakpoints when catching a fatal event might be added later for
> > Linux/Mac. Next up though is an easier way for users to install g3log as
> a
> > library
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Hurleyworks/JuceApp/pull/2#issuecomment-75623543>.
>



-- 
-Steve
http://www.hurleyworks.com

**Comment by KjellKod** [comment]
> One thing that I hit that was confusing
> was that when I set the hook to
> g2::setFatalPreLoggingHook([]{__debugbreak(); }), then there's no g3log
> file saved at all after a crash when compiled in Release mode.

How bizarre?! I will look into it, as well as making sure the names in the example is right

**Comment by KjellKod** [comment]
See inline response.

On Tue, Feb 24, 2015 at 6:51 AM, Steve Hurley <notifications@github.com>
wrote:

> Excellent!. That's very useful. One thing that I hit that was confusing
> was that when I set the hook to
> g2::setFatalPreLoggingHook([]{__debugbreak(); }), then there's no g3log
> file saved at all after a crash when compiled in Release mode.
>

__debugbreak() caused a recursive fatal crash. I've put in handling of
recursive crashes now, in case the "pre fatal logging hook" would case a
crash.   I've tested it on Windows and Linux so it should be OK on OSX too.

Cheers

Kjell

**Contact Information**
*Mobile:  +1 - 617.378.1915*

*E-mail: Hedstrom@KjellKod.cc*

**Pull request merged**
